const Constants = {
  ADD_WIN_SCORE:"ADD_WIN_SCORE",
  ADD_COINS: "ADD_COINS",
  ADD_BET:"ADD_BET",
  TOGGLE_AUTO_SPIN:"TOGGLE_AUTO_SPIN",
  SPIN:"SPIN",
  HOME:"HOME",
  SETTINGS:"SETTINGS",
  ADD_TOTAL_BET: "ADD_TOTAL_BET",
  GAME_OVER: "GAME_OVER"
}

export default Constants;